// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./io/helper.go

package io

import (
	gomock "code.google.com/p/gomock/gomock"
	io "io"
	os "os"
	time "time"
)

// Mock of Helper interface
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *_MockHelperRecorder
}

// Recorder for MockHelper (not exported)
type _MockHelperRecorder struct {
	mock *MockHelper
}

func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &_MockHelperRecorder{mock}
	return mock
}

func (_m *MockHelper) EXPECT() *_MockHelperRecorder {
	return _m.recorder
}

func (_m *MockHelper) OpenDockerfileRelative(dir string) (io.Reader, error) {
	ret := _m.ctrl.Call(_m, "OpenDockerfileRelative", dir)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockHelperRecorder) OpenDockerfileRelative(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OpenDockerfileRelative", arg0)
}

func (_m *MockHelper) OpenFileRelative(path string) (*os.File, error) {
	ret := _m.ctrl.Call(_m, "OpenFileRelative", path)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockHelperRecorder) OpenFileRelative(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OpenFileRelative", arg0)
}

func (_m *MockHelper) DirectoryRelative(dir string) string {
	ret := _m.ctrl.Call(_m, "DirectoryRelative", dir)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockHelperRecorder) DirectoryRelative(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DirectoryRelative", arg0)
}

func (_m *MockHelper) ConfigReader() io.Reader {
	ret := _m.ctrl.Call(_m, "ConfigReader")
	ret0, _ := ret[0].(io.Reader)
	return ret0
}

func (_mr *_MockHelperRecorder) ConfigReader() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ConfigReader")
}

func (_m *MockHelper) ConfigFile() string {
	ret := _m.ctrl.Call(_m, "ConfigFile")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockHelperRecorder) ConfigFile() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ConfigFile")
}

func (_m *MockHelper) LastTimeInDirRelative(_param0 string) (time.Time, error) {
	ret := _m.ctrl.Call(_m, "LastTimeInDirRelative", _param0)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockHelperRecorder) LastTimeInDirRelative(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LastTimeInDirRelative", arg0)
}

func (_m *MockHelper) LastTimeInDir(_param0 string) (time.Time, error) {
	ret := _m.ctrl.Call(_m, "LastTimeInDir", _param0)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockHelperRecorder) LastTimeInDir(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LastTimeInDir", arg0)
}
