// Automatically generated by MockGen. DO NOT EDIT!
// Source: io/virtualbox.go

package io

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of VirtualBox interface
type MockVirtualBox struct {
	ctrl     *gomock.Controller
	recorder *_MockVirtualBoxRecorder
}

// Recorder for MockVirtualBox (not exported)
type _MockVirtualBoxRecorder struct {
	mock *MockVirtualBox
}

func NewMockVirtualBox(ctrl *gomock.Controller) *MockVirtualBox {
	mock := &MockVirtualBox{ctrl: ctrl}
	mock.recorder = &_MockVirtualBoxRecorder{mock}
	return mock
}

func (_m *MockVirtualBox) EXPECT() *_MockVirtualBoxRecorder {
	return _m.recorder
}

func (_m *MockVirtualBox) CodeVolumeToVboxPath(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "CodeVolumeToVboxPath", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVirtualBoxRecorder) CodeVolumeToVboxPath(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CodeVolumeToVboxPath", arg0)
}

func (_m *MockVirtualBox) NeedPathTranslation() bool {
	ret := _m.ctrl.Call(_m, "NeedPathTranslation")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockVirtualBoxRecorder) NeedPathTranslation() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NeedPathTranslation")
}
