// Automatically generated by MockGen. DO NOT EDIT!
// Source: virtualbox.go

package io

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of VirtualBox interface
type MockVirtualBox struct {
	ctrl     *gomock.Controller
	recorder *_MockVirtualBoxRecorder
}

// Recorder for MockVirtualBox (not exported)
type _MockVirtualBoxRecorder struct {
	mock *MockVirtualBox
}

func NewMockVirtualBox(ctrl *gomock.Controller) *MockVirtualBox {
	mock := &MockVirtualBox{ctrl: ctrl}
	mock.recorder = &_MockVirtualBoxRecorder{mock}
	return mock
}

func (_m *MockVirtualBox) EXPECT() *_MockVirtualBoxRecorder {
	return _m.recorder
}

func (_m *MockVirtualBox) FSMappings() ([]SharedFolder, error) {
	ret := _m.ctrl.Call(_m, "FSMappings")
	ret0, _ := ret[0].([]SharedFolder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVirtualBoxRecorder) FSMappings() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FSMappings")
}
